routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'PagesController@getHome');
Route::get('/product/{id}/{type}/{name}', 'PagesController@getProduct');
Route::get('/category/{id}/{name}', 'PagesController@getCategory');
Route::get('/contact', 'PagesController@getContact');
Route::post('/contact/send_mail', 'PagesController@send_mail')->name('contact.send_mail');
Route::get('/news/{id}/{baslik}', 'PagesController@getNews');
Route::post('/search_page', 'PagesController@searchResults')->name('search_page');



Route::middleware(['auth'])->group(function() {
  // Anasayfa
  Route::get('/panel','HomeController@index');

  // Kategoriler
  Route::resource('/panel/categories','CategoryController');
  Route::get('/panel/delete_category_image/{id}','CategoryController@delete_category_image');

  // Özellikler
  Route::resource('/panel/attributes','AttributeController');
  Route::get('/attribute_search','AttributeController@attribute_search');

  // Etiketler
  Route::resource('/panel/tags','TagController');
  Route::get('/tag_search','TagController@tag_search');

  // Ürünler
  Route::resource('/panel/products','ProductController');
  Route::get('/panel/delete_product_image/{id}','ProductController@delete_product_image');

  Route::resource('/panel/users','UserController');
  Route::get('/panel/profile','UserController@profile')->name('profile');
  Route::post('/panel/profile/update/{user}','UserController@profile_update')->name('profile.update');

  // Haberler
  Route::resource('/panel/news','NewsController');
  Route::get('/panel/delete_news_image/{id}','NewsController@delete_news_image');

});

resources/views/panel/attributes.blade.php
@extends('layouts.panel_master')

@section('breadcrumb')


  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item active">Özellikler</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->


@endsection

@section('content')


  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 offset-md-10 text-right">
          <a href="{{ route('attributes.create') }}" class="btn btn-primary mb-3">Ekle</a>
        </div>
        <!-- /.col -->
        <div class="col-12">

          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table id="data_table" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Adı</th>
                      <th style="width:120px; min-width:120px; max-width:120px;">İşlemler</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($attributes as $attribute)
                    <tr>
                      <td>{{ $attribute->name }}</td>
                      <td class="text-center">
                        <a class="btn btn-sm btn-info mr-2" href="{{ route('attributes.edit', ['id'=>$attribute->id]) }}">Düzenle</a>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content -->



  <script>
    $(document).ready(function() {
     $("#data_table").DataTable();
    })
  </script>
@endsection

resources/views/panel/categories.blade.php
@extends('layouts.panel_master')

@section('breadcrumb')


  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item active">Kategoriler</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->


@endsection

@section('content')


  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 offset-md-10 text-right">
          <a href="{{ route('categories.create') }}" class="btn btn-primary mb-3">Ekle</a>
        </div>
        <!-- /.col -->
        <div class="col-12">

          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table id="data_table" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Adı</th>
                      <th style="width:120px; min-width:120px; max-width:120px;">İşlemler</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($categories as $category)
                    <tr>
                      <td>{{ $category->name }}</td>
                      <td class="text-center">
                        <a class="btn btn-sm btn-info mr-2" href="{{ route('categories.edit', ['id'=>$category->id]) }}">Düzenle</a>
                      </td>
                    </tr>
                      @foreach($category->subcategories as $subcategory)
                      <tr>
                        <td>{{ $category->name." > ".$subcategory->name }}</td>
                        <td class="text-center">
                          <a class="btn btn-sm btn-info mr-2" href="{{ route('categories.edit', ['id'=>$subcategory->id]) }}">Düzenle</a>
                        </td>
                      </tr>

                        @foreach($subcategory->subcategories as $sub_sub)
                          <tr>
                            <td>{{ $category->name." > ".$subcategory->name." > ".$sub_sub->name }}</td>
                            <td class="text-center">
                              <a class="btn btn-sm btn-info mr-2" href="{{ route('categories.edit', ['id'=>$sub_sub->id]) }}">Düzenle</a>
                            </td>
                          </tr>
                        @endforeach
                      @endforeach
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content -->



  <script>
    $(document).ready(function() {
       $("#data_table").DataTable();
    })
  </script>
@endsection

resources/views/panel/home.blade.php
@extends('layouts.panel_master')

@section('breadcrumb')


  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item active"><a href="/">Anasayfa</a></li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->


@endsection

@section('content')





  <script>
     $(document).ready(function() {

    })
  </script>
@endsection

resources/views/panel/news.blade.php
@extends('layouts.panel_master')

@section('breadcrumb')


  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/panel">Anasayfa</a></li>
            <li class="breadcrumb-item active">Haberler</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->


@endsection

@section('content')


  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 offset-md-10 text-right">
          <a href="{{ route('news.create') }}" class="btn btn-primary mb-3">Ekle</a>
        </div>
        <!-- /.col -->
        <div class="col-12">

          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table id="data_table" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Başlık</th>
                      <th>İçerik</th>
                      <th style="width:120px; min-width:120px; max-width:120px;">İşlemler</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($news as $news_detail)
                    <tr>
                      <td>{{ $news_detail->baslik }}</td>
                      <td>{!! $news_detail->icerik !!}</td>
                      <td class="text-center">
                        <a class="btn btn-sm btn-info mr-2" href="{{ route('news.edit', ['id'=>$news_detail->id]) }}">Düzenle</a>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content -->



  <script>
    $(document).ready(function() {
       $("#data_table").DataTable();
    })
  </script>
@endsection

resources/views/panel/products.blade.php
@extends('layouts.panel_master')

@section('breadcrumb')


  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item active">Ürünler</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->


@endsection

@section('content')


  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 offset-md-10 text-right">
          <a href="{{ route('products.create') }}" class="btn btn-primary mb-3">Ekle</a>
        </div>
        <!-- /.col -->
        <div class="col-12">

          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table id="data_table" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Adı</th>
                      <th>Kategorisi</th>
                      <th>İlişkili Ürün</th>
                      <th style="width:120px; min-width:120px; max-width:120px;">İşlemler</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($products as $product)
                    <tr>
                      <td>{{ $product->name }}</td>
                      <td>
                        @if($product->category)
                          @if($product->category->parent)
                            @if($product->category->parent->parent)
                              {{ $product->category->parent->parent->name }} >
                            @endif
                          {{ $product->category->parent->name." > ".$product->category->name }}
                          @elseif($product->category)
                          {{ $product->category->name }}
                          @endif
                        @endif
                      </td>
                      <td>
                        @if($product->related_products)
                          {{ $product->related_products->name }}
                        @endif
                      </td>
                      <td class="text-center">
                        <a class="btn btn-sm btn-info mr-2" href="{{ route('products.edit', ['id'=>$product->id]) }}">Düzenle</a>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content -->



  <script>
    $(document).ready(function() {
      $("#data_table").DataTable();
    })
  </script>
@endsection

resources/views/panel/tags.blade.php
@extends('layouts.panel_master')

@section('breadcrumb')


  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item active">Etiketler</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->


@endsection

@section('content')


  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 offset-md-10 text-right">
          <a href="{{ route('tags.create') }}" class="btn btn-primary mb-3">Ekle</a>
        </div>
        <!-- /.col -->
        <div class="col-12">

          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table id="data_table" class="table table-bordered table-striped">
                  <thead>
                    <tr>
                      <th>Adı</th>
                      <th style="width:120px; min-width:120px; max-width:120px;">İşlemler</th>
                    </tr>
                  </thead>
                  <tbody>
                    @foreach($tags as $tag)
                    <tr>
                      <td>{{ $tag->name }}</td>
                      <td class="text-center">
                        <a class="btn btn-sm btn-info mr-2" href="{{ route('tags.edit', ['id'=>$tag->id]) }}">Düzenle</a>
                      </td>
                    </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content -->



  <script>
    $(document).ready(function() {
     $("#data_table").DataTable();
    })
  </script>
@endsection

resources/views/panel/users.blade.php
@extends('layouts.panel_master')

@section('breadcrumb')

<!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">Anasayfa</a></li>
            <li class="breadcrumb-item active">Kullanıcılar</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
@endsection

@section('content')


  <!-- Main content -->
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-2 offset-md-10">

          <a href="{{route('register')}}" class="btn btn-primary btn-block mb-3">Ekle</a>

        </div>
        <!-- /.col -->
        <div class="col-12">

          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table id="users_table" class="table table-bordered table-striped">
                    <thead>
                        <tr>
                            <th>İsim</th>
                            <th style="width:60px; min-width:60px; max-width:60px;">İşlem</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($users as $user)

                            <tr>
                                <td>{{ $user->name }}</td>
                                <td class="text-center">
                                  <a class="btn btn-sm btn-info mr-3" href="{{ route('users.edit', ['id'=>$user->id]) }}">Düzenle</a>
                                </td>
                            </tr>

                        @endforeach
                    </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->
    </div>
  </div>
  <!-- /.content -->

    <script>
        $(document).ready(function() {
          $("#users_table").DataTable();
        })
    </script>

@endsection